### ISSUE TITLE
Missing icon for slime rancher plortable edition 0100b9c0148d0000

### ISSUE THREAD

**Issue by Pokilokui** [DelxHQ/ClientSwitchPresence#4]
Missing icon for slime rancher plortable edition 0100b9c0148d0000
![0100b9c0148d0000](https://user-images.githubusercontent.com/101603910/192587970-b54f3fd5-40a3-4dbd-83c8-6027d60ac31c.jpg)

**Comment by DelxHQ** [comment]
So sorry for the late response. I've been super busy lately. Game icon has been added. Thank you!
